---
# Source: longhorn/templates/deployment-ui.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: 66storedge
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.4.0-dev
    app: longhorn-ui
  name: longhorn-ui
  namespace: longhorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 66storedge
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/version: v1.4.0-dev
        app: longhorn-ui
    spec:
      containers:
        - name: longhorn-ui
          image: longhornio/longhorn-ui:master-head
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx/
            - name: nginx-config
              mountPath: /var/config/nginx/
            - name: var-run
              mountPath: /var/run/
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: LONGHORN_MANAGER_IP
              value: "http://longhorn-backend:9500"
            - name: LONGHORN_UI_PORT
              value: "8000"
      volumes:
        - emptyDir: {}
          name: nginx-cache
        - emptyDir: {}
          name: nginx-config
        - emptyDir: {}
          name: var-run
