apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-multipathd-disable
  namespace: longhorn-system
  labels:
    app: longhorn-multipathd-disable
  annotations:
    command: &cmd sudo systemctl stop multipathd && sudo systemctl disable multipathd && if [ $? -eq 0 ]; then echo "multipathd successfully disabled"; else echo "multipathd disable failed error code $?"; fi
spec:
  selector:
    matchLabels:
      app: longhorn-multipathd-disable
  template:
    metadata:
      namespace: longhorn-system
      labels:
        app: longhorn-multipathd-disable
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
        - name: multipathd-disable
          command:
            - nsenter
            - --mount=/proc/1/ns/mnt
            - --
            - bash
            - -c
            - *cmd
          image: alpine:3.12
          securityContext:
            privileged: true
      containers:
        - name: sleep
          image: k8s.gcr.io/pause:3.1
  updateStrategy:
    type: RollingUpdate
