---
# Source: longhorn/templates/daemonset-sa.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: 66storedge
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.4.0-dev
    app: longhorn-manager
  name: longhorn-manager
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 66storedge
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/version: v1.4.0-dev
        app: longhorn-manager
    spec:
      initContainers:
        - name: wait-longhorn-admission-webhook
          image: us-central1-docker.pkg.dev/lmurillo-playground/longhorn/longhorn-manager:0eec020d-dirty
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" -k https://longhorn-admission-webhook:9443/v1/healthz) != "200" ]; do echo waiting; sleep 2; done']
      containers:
        - name: longhorn-manager
          image: us-central1-docker.pkg.dev/lmurillo-playground/longhorn/longhorn-manager:0eec020d-dirty
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - longhorn-manager
            - -d
            - daemon
            - --engine-image
            - "us-central1-docker.pkg.dev/lmurillo-playground/longhorn/longhorn-engine:691122a-dirty"
            - --instance-manager-image
            - "us-central1-docker.pkg.dev/lmurillo-playground/longhorn/longhorn-instance-manager:v2_20221012"
            - --share-manager-image
            - "us-central1-docker.pkg.dev/lmurillo-playground/longhorn/longhorn-share-manager:v_20221012"
            - --backing-image-manager-image
            - "us-central1-docker.pkg.dev/lmurillo-playground/longhorn/backing-image-manager:v3_20221012"
            - --manager-image
            - "us-central1-docker.pkg.dev/lmurillo-playground/longhorn/longhorn-manager:0eec020d-dirty"
            - --service-account
            - longhorn-service-account
          ports:
            - containerPort: 9500
              name: manager
          readinessProbe:
            tcpSocket:
              port: 9500
          volumeMounts:
            - name: dev
              mountPath: /host/dev/
            - name: proc
              mountPath: /host/proc/
            - name: longhorn
              mountPath: /var/lib/longhorn/
              mountPropagation: Bidirectional
            - name: longhorn-grpc-tls
              mountPath: /tls-files/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: dev
          hostPath:
            path: /dev/
        - name: proc
          hostPath:
            path: /proc/
        - name: longhorn
          hostPath:
            path: /var/lib/longhorn/
        - name: longhorn-grpc-tls
          secret:
            secretName: longhorn-grpc-tls
            optional: true
      serviceAccountName: longhorn-service-account
  updateStrategy:
    rollingUpdate:
      maxUnavailable: "100%"
